### ISSUE TITLE
Containerize application and run on scheduler

### ISSUE THREAD

**Issue by yuwtennis** [yuwtennis/tennis-tournament-schedules#1]
# Tasks

- [ ]  Add dockerfile
- [ ]  Start github package
- [ ]  Write CI/CD with gihub action
- [ ]  Run on local docker
